#!/usr/bin/env bash
set -euo pipefail

build_dir="${1:-build}"

rm -rf "${build_dir}"

cmake -S . -B "${build_dir}" -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_LIBS_PRECOMPILED=OFF \
  -DWITH_CYCLES_ALEMBIC=OFF \
  -DWITH_CYCLES_EMBREE=OFF \
  -DWITH_CYCLES_OPENIMAGEDENOISE=OFF \
  -DWITH_CYCLES_OPENSUBDIV=OFF \
  -DWITH_CYCLES_OPENVDB=OFF \
  -DWITH_CYCLES_NANOVDB=OFF \
  -DWITH_CYCLES_OSL=OFF \
  -DWITH_USD=OFF \
  -DWITH_CYCLES_USD=OFF \
  -DWITH_CYCLES_HYDRA_RENDER_DELEGATE=OFF \
  -DWITH_STRICT_BUILD_OPTIONS=ON \
  -DWITH_CYCLES_DEVICE_CUDA=ON \
  -DWITH_CYCLES_DEVICE_OPTIX=ON \
  -DWITH_CYCLES_DEVICE_HIP=OFF \
  -DWITH_CYCLES_DEVICE_ONEAPI=OFF

grep -E 'WITH_(USD|CYCLES_USD|CYCLES_HYDRA_RENDER_DELEGATE|CYCLES_DEVICE_CUDA|CYCLES_DEVICE_OPTIX|STRICT_BUILD_OPTIONS)|OPTIX_ROOT_DIR' "${build_dir}/CMakeCache.txt" || true
